name: Playground

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker-setup-version:
        description: "Version of docker-setup to use"
        required: true
        default: "latest"
      docker-setup-log-level:
        description: "Log level"
        required: true
        default: "info"

jobs:

  release:
    name: Playground
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install docker-setup
      uses: nicholasdille/docker-setup-action@main
      with:
        version: "2.2.56"
        prefix: helper
        tools: go
        log-level: debug

    - name: Reference
      run: |
        bash test.sh "bash demo.sh"

    - name: Play
      env:
        CGO_ENABLED: 0
      run: |
        helper/usr/local/bin/go build -o demo ./cmd/demo
        bash test.sh "./demo"
